backend: # Set up your backend
  name: git-gateway
  branch: blog-dev

  #local_backend: true # Optional if you want to use the local proxy mode

publish_mode: editorial_workflow
media_folder: media    # I'm not using these default media directories at the moment.
public_folder: /media

collections:
  - name: "tags"
    label: "Tags"
    folder: "/blog/content/tags/tags"
    create: true
    delete: true
    format: "yml"
    identifier_field: "name"
    editor:
      preview: false
    fields:
      - { label: 'Name', name: "name", widget: "string" }
  - name: "posts"
    label: "Posts"
    folder: "/blog/content/posts"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "images"
    public_folder: "./images"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", valueField: "name", searchFields: ["name"] }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "relation", collection: "tags", valueField: "name", searchFields: ["name"], multiple: true}
      - { label: "Hero", name: "hero", widget: "image" }
      - label: "Jupyter"
        name: "jupyter"
        widget: "relation"
        collection: "jupyter_files"
        valueField: "items"
        searchFields: ["items"]
        multiple: true
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "authors"
    label: "Authors"
    folder: "/blog/content/authors/authors"
    create: true
    delete: true
    format: "yml"
    identifier_field: "name"
    media_folder: "avatars"
    public_folder: "./avatars"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "string" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - { label: "Social", name: "social", widget: "list", collapsed: false, field: { label: "URL", name: "url", widget: "string" } }
  - name: "jupyter_files"
    label: "Jupyter Files"
    folder: "/blog/content/posts/jupyter"
    path: "{{name}}/directory"
    create: true
    format: "yml"
    identifier_field: "name"
    delete: true
    media_folder: "files"
    public_folder: "./files"
    editor:
      preview: false
    fields:
      - { label: "Author", name: "name", widget: "relation", collection: "authors", valueField: "name", searchFields: ["name"] }
      - label: "Items"
        name: "items"
        widget: "list"
        fields:
          - { label: "Name", name:"title", widget: "string"}
          - { label: "file", name:"file", widget: "file"}
